### ISSUE TITLE
Tracking issue: Migration to React 18

### ISSUE THREAD

**Issue by BasixKOR** [planetarium/9c-launcher#1480]
## Prerequisites
 - [ ] Get rid of react-router v5, or migrate to v6
   - [ ] V2 interface (should be migrated)
   * V1 interface (should be removed)
   * Monster Collection V1 (should be removed)
   * Transfer uses own routing implementation.

## Steps
- [ ] Bump packages to React 18 compatible ones
- [ ] Try concurrent features on some parts that needs it
  - I'm planning to use `useDeferredValue` on tip indicator, since it causes a ton of UI updates.

**Comment by BasixKOR** [comment]
I expect that using the concurrent features on certain parts of the launcher could improve the perceived performance quite a lot. We need to figure out which components are causing frequent updates first though.
