### ISSUE TITLE
Adapt on Multichain environment

### ISSUE THREAD

**Issue by Akamig** [planetarium/9c-launcher#2331]
## TODO
- [x] connect right genesis block for different chains (out of config.json), from PNS expected
- [x] Add chain selector on
  - [x] LoginView
  - [x] GetPatronView
- [x] Send portal additional `planet` query param on Get Patron.

**Comment by Akamig** [comment]
#2341 is not merged due to release date issues, but as speaking of adapt on multiplanetary, it can safely be concluded as managed. closing.
